import { Card, Project } from './types';

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'project-1',
    name: 'Redesign Editorial',
    description: 'Reformulação visual e estética do periódico conceitual de arte contemporânea.',
    itemCount: 12,
  },
  {
    id: 'project-2',
    name: 'Brand Moodboard',
    description: 'Direção criativa de marca de moda minimalista com base em conceitos japoneses.',
    itemCount: 8,
  },
  {
    id: 'project-3',
    name: 'Arquitetura Brutal',
    description: 'Estudo fotográfico e analítico sobre o espaço negativo no brutalismo paulista.',
    itemCount: 4,
  }
];

export const INITIAL_CARDS: Card[] = [
  {
    id: 'card-wabi-sabi',
    type: 'concept',
    title: 'Wabi-sabi',
    content: 'Beleza encontrada na imperfeição e na transitoriedade. A valorização das marcas do tempo, das assimetrias e da simplicidade rústica como manifesto contra o consumismo descartável.',
    tags: ['estética', 'filosofia', 'japonês'],
    date: '28 mai 2026',
    context: 'concept',
    projects: ['project-1', 'project-2'],
  },
  {
    id: 'card-1',
    type: 'observation',
    title: 'A fadiga da decisão',
    content: 'Cada escolha adicional degrada a capacidade de decidir. Sistemas de curadoria diminuem a sobrecarga cognitiva do usuário por meio de restrições expressivas.',
    tags: ['psicologia', 'ux'],
    date: '28 mai 2026',
    context: 'concept',
  },
  {
    id: 'card-2',
    type: 'insight',
    title: 'Cultura Organizacional',
    content: 'A cultura corporativa funciona como estratégia real no café da manhã: quando expressa de forma ritualística, orienta a tomada de decisões criativas sem guias explícitos.',
    tags: ['estratégia', 'cultura'],
    date: '27 mai 2026',
    context: 'management',
  },
  {
    id: 'card-3',
    type: 'reference',
    title: 'Design Brutalista',
    content: 'O uso expressivo do espaço negativo na arquitetura moderna brutalista, articulando a luz natural como elemento estrutural e volumétrico ativo.',
    tags: ['estética', 'brutalismo'],
    date: '26 mai 2026',
    source: 'Architectural Review',
    context: 'Arquitetura Brutal',
    projects: ['project-3'],
  },
  {
    id: 'card-4',
    type: 'insight',
    title: 'O minimalismo funcional',
    content: 'O verdadeiro minimalismo não é a ausência de matéria, mas sim uma ferramenta consciente de preservação de energia cognitiva e respeito ao foco humano.',
    tags: ['design', 'foco'],
    date: '25 mai 2026',
    context: 'concept',
    projects: ['project-1', 'project-2'],
  },
  {
    id: 'card-5',
    type: 'image',
    title: 'Cor nas cidades',
    content: 'Fachadas antigas restauradas com paletas cromáticas mais corajosas do que os tons cinzas corporativos contemporâneos.',
    tags: ['urbano', 'estética', 'cor'],
    date: '24 mai 2026',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600',
    context: 'mural',
    projects: ['project-2'],
  },
  {
    id: 'card-6',
    type: 'trend',
    title: 'Slow Living',
    content: 'Desacelerar propositalmente como manifesto de resposta ao excesso de estímulos digitais e pressões por ritmo frenético de entregas.',
    tags: ['comportamento', 'tendência'],
    date: '22 mai 2026',
    context: 'culture',
  },
  {
    id: 'card-7',
    type: 'concept',
    title: 'Tipografia como voz',
    content: 'A escolha tipográfica transmite valores, tons de voz e mensagens subliminares muito antes de o usuário ler voluntariamente a primeira palavra.',
    tags: ['design', 'tipografia'],
    date: '21 mai 2026',
    context: 'brandbook',
    projects: ['project-1'],
  },
  {
    id: 'card-8',
    type: 'sketch',
    content: 'Roteiros alternativos e redes de pensamentos em múltiplos palcos. Ideias têm ramificações fluidas e dinâmicas.',
    tags: ['processo', 'criatividade'],
    date: '20 mai 2026',
    context: 'concept',
  },
  {
    id: 'card-9',
    type: 'insight',
    title: 'Cansaço como estética',
    content: 'A romantização do esgotamento físico na cultura visual contemporânea, explorando como o cansaço corporal é estilizado na fotografia editorial de luxo.',
    tags: ['cultura', 'tendência'],
    date: '18 mai 2026',
    context: 'culture',
    projects: ['project-1'],
  },
  {
    id: 'card-10',
    type: 'trend',
    title: 'Slow design movement',
    content: 'Um retorno planejado ao design tátil e analógico. Priorizar a longevidade dos materiais, os processos humanos de feitura e a textura contra a padronização digital plana.',
    tags: ['design', 'filosofia', 'tátil'],
    date: '17 mai 2026',
    context: 'editorial',
    projects: ['project-1', 'project-2'],
  },
  {
    id: 'card-11',
    type: 'concept',
    title: 'Brutalism in Typography',
    content: 'Investigando a ascensão de composições tipográficas robustas, cruas e sem polimento, que utilizam quebras intencionais de grid nas páginas digitais modernas.',
    tags: ['tipografia', 'web'],
    date: '15 mai 2026',
    context: 'curations',
  },
  {
    id: 'card-12',
    type: 'quote',
    title: '"Why linear narratives are replacing..."',
    content: 'Por que as narrativas sequenciais no formato cinematográfico estão tomando o lugar do tradicional moodboard bidimensional nos conselhos de direção criativa de elite.',
    tags: ['processo', 'agência', 'direção'],
    author: 'Creative Dir, Studio M',
    date: '12 mai 2026',
    context: 'pitching',
  },
  {
    id: 'card-13',
    type: 'reference',
    title: 'Tactile Digital Interfaces',
    content: 'Uso experimental de granulações de papel, ruídos sutis e microtexturas na interface de usuário (UI) como método tátil de aliviar a fadiga visual das telas espelhadas.',
    tags: ['ui', 'estética', 'textura'],
    source: 'Awwwards Blog',
    date: '10 mai 2026',
    context: 'research',
    projects: ['project-2'],
  },
  {
    id: 'card-14',
    type: 'trend',
    title: 'Neo-Archive',
    content: 'A prática contemporânea de arquivamento digital, onde plataformas individuais são tratadas como portfólios-museus curados milimetricamente pelo usuário.',
    tags: ['curadoria', 'tendência'],
    date: '08 mai 2026',
    context: 'philosophy',
  },
  {
    id: 'card-15',
    type: 'observation',
    title: 'Typography as Image',
    content: 'O momento em que caracteres e glifos gigantes de fontes serifadas preenchem todo o espaço visual do card, transformando-se eles mesmos na composição gráfica focal.',
    tags: ['tipografia', 'visual'],
    date: '05 mai 2026',
    context: 'editorial',
  }
];
